applications:
  medusa:
    source:
      root: "/"
    type: "nodejs:20"

    relationships:
      database: "postgresql:postgresql"
      redis: "redis:redis"
      search: "opensearch:opensearch"

    web:
      commands:
        start: |
          export ADMIN_CORS=$(echo $PLATFORM_ROUTES | base64 --decode | jq -r 'keys[0]')
          export STORE_CORS=$(echo $PLATFORM_ROUTES | base64 --decode | jq -r 'keys[0]')

          npx medusa start
      upstream:
        socket_family: tcp
      locations:
        "/":
          passthru: true

    # Add required environment variables (set these via Upsun CLI or UI)
    variables:
      env:
        NODE_ENV: production

    build:
      flavor: none

    dependencies:
      nodejs:
        yarn: "^1.22.0"

    hooks:
      build: |
        set -eux
        yarn install
        yarn build

      deploy: |
        set -eux
        npx medusa migrations run

services:
  postgresql:
    type: postgresql:15
    disk: 2048

  redis:
    type: redis:7.0

  opensearch:
    type: opensearch:2
    disk: 1024

routes:
  "https://{default}/":
    type: upstream
    upstream: "medusa:http"
  "https://www.{default}":
    type: redirect
    to: "https://{default}/"
